config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'hotels#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :hotels do
    collection do
      get 'search'
    end
  end
   # get '/users/edit', to: 'users#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["address", "category", "category_id", "created_at", "describe", "id", "image", "location_id", "name", "title", "updated_at"]
  end
  mount_uploader :image, ImageUploader
  scope :search_by_category, ->(category) { where(category: category) }
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :hotel 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  #新規登録時のストロングパラメータに「username, job, profile」カラムの追加
  def configure_permitted_parameters
      #新規登録時のストロングパラメータにカラムの追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :avatar, :is_admin])
      #編集時のストロングパラメータにカラムの追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :avatar, :is_admin])
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :deny_non_admin_users, only: [:new, :edit]
  before_action :set_q, only: [:index, :search]
  before_action :set_hotel, only: [:show,:edit,:update]
    
  def index
     @hotels = Hotel.all
     @categories = Hotel.where.not(category: nil).pluck(:category).uniq
     @address = Hotel.where.not(address: nil).pluck(:address).uniq
  end

  def new
    @hotel = Hotel.new
  end
  
  def show
  end
  
  def create
     @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to root_path, flash: {notice: "投稿が完了しました。"}
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @hotel.update(hotel_params)
      redirect_to root_path, flash: {notice: "更新が完了しました。"}
    else
      render :edit
    end
  end
  
  def search
    @results = @q.result
  end

  private
  
  def set_q
    @q = Hotel.ransack(params[:q])
  end
  
  def set_hotel
    @hotel = Hotel.find(params[:id])
  end
  
  def hotel_params
    params.require(:hotel).permit(:name,:image,:address,:describe,:title,:category)
  end

  def deny_non_admin_users
    unless current_user && current_user.is_admin?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-10 col-md-6">
      <%= form_with model: hotel, local: true, class: 'text-center mb-5' do |f| %>
        <%= render 'layouts/validation_error', instance: hotel %>

        <div class="div-title">
          <div class="text-start">
            <%= f.label :name, class: 'title-p fw-bold text-main', value: 'ホテルの名前' %>
          </div>
          <%= f.text_field :name, class: 'form-control py-md-3 rounded bg-white box-shadow mb-3' %>
        </div>
        
        <div class="div-title">
          <div class="text-start">
            <%= f.label :title, class: 'title-p fw-bold text-main', value: 'ホテルのタイトル' %>
          </div>
          <%= f.text_field :title, class: 'form-control py-md-3 rounded bg-white box-shadow mb-3' %>
        </div>
        
        <div class="div-title">
          <div class="text-start">
            <%= f.label :describe, class: 'title-p fw-bold text-main', value: 'ホテルについて' %>
          </div>
          <%= f.text_area :describe, class: 'form-control py-md-3 rounded bg-white box-shadow mb-3' %>
        </div>
        
        <div class="img-select">
          <div class="text-start">
            <%= f.label :image, class: 'fw-bold mb-3 text-main', value: 'サムネイル画像' %>
          </div>
          <%= f.file_field :image %>
        </div>
        
        <div class="py-3">
          <div class="text-start mb-3">
            <%= f.label :address, class: 'fw-bold rounded text-main', value: 'ホテルの所在地（例：東京都浅草）' %>
          </div>
          <%= f.text_field :address, class: 'form-control tag-text box-shadow bg-white' %>
        </div>
        
        <div class="py-3">
          <div class="text-start mb-3">
            <%= f.label :category, class: 'fw-bold rounded text-main', value: 'カテゴリー' %>
          </div>
            <%= f.text_field :category, class: 'form-control tag-text box-shadow bg-white',placeholder: "一旦はカテゴリーを一つのみ登録" %>
        </div>
        
        <div class="col-12 d-flex justify-content-center">
          <%= f.submit '登録する', class: 'btn d-block rounded fw-bold box-shadow text-white mt-4 px-5 py-3 fs-6 bg-purple' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/hotels/edit.html.erb
<%= render 'form', hotel: @hotel %>

app/views/hotels/index.html.erb
<section class="hero d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 mx-auto text-center">
          <h1 class="display-4 text-white my-3">「ホカンス」を楽しもう！</h1>
          <p class="text-white">「ホカンス」とはホテルでバケーション、休暇を楽しむという造語です。<br>都内にはホカンスが楽しめるホテルがたくさんあります！
          </p>
        </div>
      </div>
    </div>
</section>

<section id="search" class="py-4 text-center container-fluid" >
    <div class="row py-lg-1">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h4 class="fw-light mx-auto">「ホカンス」したい都内のホテルを最寄駅とカテゴリから探してみましょう</h1>
      
          <%= search_form_for @q, url: search_hotels_path, html: { class: "needs-validation text-center" } do |f| %>
            <div class="row g-3 d-flex justify-content-center">
              <div class="col-md-10 d-flex row">
                <div class="col-md-6 ">
                  <%= f.collection_select :address_cont, @address, :itself, :itself, { prompt: "都内のエリアを選択"}, {class: "form-select my-3", style: "height: 48px;", id: "country" } %>
                </div>
              
                <p class="col-md-1 my-4">✖️</p>
    
                <div class="col-md-5 ">
                  <%= f.collection_select :category_cont, @categories, :itself, :itself, {prompt: "カテゴリを選択"}, {class: "form-select my-3",  style: "height: 48px;", id: "state" } %>
                </div>
              </div>
              
              <div class="col-md-2">
                <%= f.submit '検索', class: 'btn text-white btn-lg', style: 'background-color:#2146c7;' %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </section>
  
<section id="category">
  <div class="container">
    <div class="d-flex justify-content-between my-5">
      <p class="text-left text-black fs-3">人気のカテゴリ</p>
      <p class="text-right my-2" style="color:#2146c7;text-decoration:underline;">すべてのカテゴリを見る</p>
    </div>
      
      <div class="row g-4">
        
         <div class="col-md-3 example">
            <div class="card">
              <%= image_tag 'main_visual.jpg', class: 'card-image' %>
              <div class="card-img-overlay">
                <p class="my-5" style="line-height:1;">#南国リゾート気分でのんびりできる</p>
              </div>
            </div>
          </div>
        
         <div class="col-md-3  example">
            <div class="card">
              <%= image_tag 'main_visual.jpg', class: 'card-image' %>
              <div class="card-img-overlay">
                <p class="my-5" style="line-height:1;">#部屋から絶景オーシャンビューが見渡せる</p>
              </div>
            </div>
          </div>
          
         <div class="col-md-3  example">
            <div class="card">
              <%= image_tag 'main_visual.jpg', class: 'card-image' %>
              <div class="card-img-overlay">
                <p class="my-5" style="line-height:1;">#客室に露天風呂がある</p>
              </div>
            </div>
          </div>
          
         <div class="col-md-3  example">
            <div class="card">
              <%= image_tag 'main_visual.jpg', class: 'card-image' %>
              <div class="card-img-overlay">
                <p class="my-5" style="line-height:1;">#テラスでくつろげる</p>
              </div>
            </div>
          </div>      
          
         <div class="col-md-3  example">
            <div class="card">
              <%= image_tag 'main_visual.jpg', class: 'card-image' %>
              <div class="card-img-overlay">
                <p class="my-5" style="line-height:1;">#記念日にぴったり</p>
              </div>
            </div>
          </div>
        
         <div class="col-md-3  example">
            <div class="card">
              <%= image_tag 'main_visual.jpg', class: 'card-image' %>
            <div class="card-img-overlay">
              <p class="my-5" style="line-height:1;">#オールインクールシブ</p>
            </div>
          </div>
          </div>
          
         <div class="col-md-3  example">
              <div class="card">
                <%= image_tag 'main_visual.jpg', class: 'card-image' %>
              <div class="card-img-overlay">
                <p class="my-5" style="line-height:1;">#オールインクールシブ</p>
              </div>
            </div>
          </div>
          
         <div class="col-md-3  example">
            <div class="card">
              <%= image_tag 'main_visual.jpg', class: 'card-image' %>
            <div class="card-img-overlay">
              <p class="my-5" style="line-height:1;">#オールインクールシブ</p>
            </div>
          </div>
          </div>
          
      </div>
      
      <hr class="my-4">
        <p class="text-center" style="color:#2146c7;">すべてのカテゴリをみる</p>
      <hr class="my-4">
  </div>
</section>
  
<section id="team" class="py-5">
    <div class="container">
      <div class="row">
        <div class="d-flex justify-content-between my-5">
          <p class="text-left text-black fs-3">登録ホテル一覧</p>
          <p class="text-right my-2" style="color:#2146c7;text-decoration:underline;">すべてのホテルを見る</p>
        </div>
      </div>

      <div class="row">
        <% @hotels.each do |hotel| %>
          
            <div class="col-md-6 my-2">
              <div class="register_hotel card card-skin">
                <%= link_to hotel_path(hotel) do %>
                  <div class="card__imgframe" style="background-image: url('<%= image_url(hotel.image) %>')"></div>
                <% end %>
                <div class="card__textbox">
                  <div class="card__titletext">
                    <%= hotel.title %>
                  </div>
                  <p class="text-secondary"><%= hotel.address %></p>
                  <div class="card__overviewtext">
                    <%= hotel.describe %>
                  </div>
                  <p class="text-secondary small" style="font-size: 6px;">#<%= hotel.category %></p>
                </div>
              </div>
            </div>
          
          <div class="col-md-6 my-2">
            <div class="register_hotel card card-skin">
              <div class="card__imgframe"></div>
              <div class="card__textbox">
                <div class="card__titletext">
                  そらの気分を味わう宿
                </div>
                <p class="text-secondary">台東区浅草</p>
                <div class="card__overviewtext">
                  世界自然遺産に登録された奄美大島の青い海が広がり、ホテル前のヤドリ浜には幸せを運ぶと言われるウミガメが生息。白い砂浜とサンゴ礁の美しい海岸が味わえます
                </div>
                <p class="text-secondary small" style="font-size: 6px;">#オールインクルーシブ#客室に露天風呂がある</p>
              </div>
            </div>
          </div>
        
          <div class="col-md-6 my-2">
            <div class="register_hotel card card-skin">
              <div class="card__imgframe"></div>
              <div class="card__textbox">
                <div class="card__titletext">
                  そらの気分を味わう宿
                </div>
                <p class="text-secondary">台東区浅草</p>
                <div class="card__overviewtext">
                  世界自然遺産に登録された奄美大島の青い海が広がり、ホテル前のヤドリ浜には幸せを運ぶと言われるウミガメが生息。白い砂浜とサンゴ礁の美しい海岸が味わえます
                </div>
                <p class="text-secondary small" style="font-size: 6px;">#オールインクルーシブ#客室に露天風呂がある</p>
              </div>
            </div>
          </div>
        
          <div class="col-md-6 my-2">
            <div class="register_hotel card card-skin">
              <div class="card__imgframe"></div>
              <div class="card__textbox">
                <div class="card__titletext">
                  そらの気分を味わう宿
                </div>
                <p class="text-secondary">台東区浅草</p>
                <div class="card__overviewtext">
                  世界自然遺産に登録された奄美大島の青い海が広がり、ホテル前のヤドリ浜には幸せを運ぶと言われるウミガメが生息。白い砂浜とサンゴ礁の美しい海岸が味わえます
                </div>
                <p class="text-secondary small" style="font-size: 6px;">#オールインクルーシブ#客室に露天風呂がある</p>
              </div>
            </div>
          </div>
        
        <% end  %>
      </div>
    
    
    <hr class="my-4">
      <p class="text-center" style="color:#2146c7;">すべてのホテルをみる</p>
    <hr class="my-4">
    </div>
  </section>

app/views/hotels/memo.html.erb
<section class="py-4 text-center container" >
    <div class="row">
      <div class="">
        <h1>ホテルを検索</h1>
        
          <%= search_form_for @q, url: search_hotels_path do |f| %>
            <%= f.label :address_cont, '都内のエリアを選択' %>
            <%= f.collection_select :address_cont, @address, :itself, :itself, prompt: "都内のエリアを選択" %>
            
            <%= f.label :category_cont, 'カテゴリを選択' %>
            <%= f.collection_select :category_cont, @categories, :itself, :itself, prompt: "カテゴリを選択" %>
            <%#= f.collection_select :category_id_cont, Category.where.not(id: 0), :id, :name, include_blank: "カテゴリーの選択", class:"search-select-box"  %>
            <%= f.submit '検索' %>
          <% end %>
          
      </div>
    </div>    
  </section>

app/views/hotels/new.html.erb
<%= render 'form', hotel: @hotel %>

app/views/hotels/search.html.erb
<section id="team" class="py-5">
    <div class="container">
      <div class="row">
        <div class="d-flex justify-content-between my-5">
          <p class="text-left text-black fs-3">検索結果</p>
          <p class="text-right my-2" style="color:#2146c7;text-decoration:underline;">すべてのホテルを見る</p>
        </div>
      </div>

      <div class="row">
        <% @results.each do |hotel| %>
            <div class="col-md-6 my-2">
              <div class="register_hotel card card-skin">
                <div class="card__imgframe" style="background-image: url('<%= image_url(hotel.image) %>')"></div>
                <div class="card__textbox">
                  <div class="card__titletext">
                    <%= hotel.title %>
                  </div>
                  <p class="text-secondary"><%= hotel.address %></p>
                  <div class="card__overviewtext">
                    <%= hotel.describe %>
                  </div>
                  <p class="text-secondary small" style="font-size: 6px;">#<%= hotel.category %></p>
                </div>
              </div>
            </div>
        <% end  %>
      </div>
      
      <hr class="my-4">
        <p class="text-center" style="color:#2146c7;">すべてのホテルをみる</p>
      <hr class="my-4">
    </div>
  </section>

app/views/hotels/show.html.erb
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
  </head>
  
  <div class="container px-4 py-5">
    <%= image_tag @hotel.image.url, class: "d-block mx-lg-auto img-fluid", alt: "Bootstrap Themes", width: 400, height: 250, loading: "lazy" %>
    <h2 class="pb-2 border-bottom"><%= @hotel.name %></h2>

    <div class="row row-cols-1 row-cols-md-2 align-items-md-center g-5 py-5">
      <div class="col d-flex flex-column align-items-start gap-2">
        <h3 class="fw-bold"><%= @hotel.title %></h3>
        <p class="text-muted"><%= @hotel.describe %></p>
        <a href="#" class="btn btn-lg text-white" style=" background-color:#2146C7;">ホームページを見る</a>
      </div>

      <div class="col">
        <div class="row row-cols-1 row-cols-sm-2 g-4">
          <div class="col d-flex flex-column gap-2">
            <div class="feature-icon-small d-inline-flex align-items-center justify-content-center bg-gradient fs-4 rounded-3" style=" background-color:#2146C7;">
              <svg class="bi" width="1em" height="1em">
                <use xlink:href="#collection" />
              </svg>
            </div>
            <h4 class="fw-semibold mb-0">所在地</h4>
            <p class="text-muted"><%= @hotel.address %></p>
          </div>

          <div class="col d-flex flex-column gap-2">
            <div class="feature-icon-small d-inline-flex align-items-center justify-content-center  bg-gradient fs-4 rounded-3" style=" background-color:#2146C7;">
              <svg class="bi" width="1em" height="1em">
                <use xlink:href="#gear-fill" />
              </svg>
            </div>
            <h4 class="fw-semibold mb-0">カテゴリー</h4>
            <p class="text-muted"><%= @hotel.category %></p>
          </div>

          <div class="col d-flex flex-column gap-2">
            <div class="feature-icon-small d-inline-flex align-items-center justify-content-center  bg-gradient fs-4 rounded-3" style=" background-color:#2146C7;">
              <svg class="bi" width="1em" height="1em">
                <use xlink:href="#speedometer" />
              </svg>
            </div>
            <h4 class="fw-semibold mb-0">タイトル</h4>
            <p class="text-muted"><%= @hotel.title %></p>
          </div>

          <div class="col d-flex flex-column gap-2">
            <div class="feature-icon-small d-inline-flex align-items-center justify-content-center  bg-gradient fs-4 rounded-3" style=" background-color:#2146C7;">
              <svg class="bi" width="1em" height="1em">
                <use xlink:href="#table" />
              </svg>
            </div>
            <h4 class="fw-semibold mb-0">説明</h4>
            <p class="text-muted"><%= @hotel.describe %></p>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= 'success' if key == 'notice' %><%= 'danger' if key == 'alert' %> vw-100 text-center" role="alert" style="top: 56px;">
    <p><%= value %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-5">
  <div class="row">
    <div class="col text-white" style="background-color:#0008C1 ;">
      <p class="text-white text-center my-2" style="font-size: 12px;">©2023 HokaSearch All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light navbar-expand-md fixed-top bg-white py-4">
  <div class="container">
    <div class="col">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <%#= link_to new_user_session_path do %>
            <%= image_tag 'logo-img.png', class: 'img-fluid', width: '50px' %>
            <%= image_tag 'logo-title.png', class: 'img-fluid', width: '300px' %>
          <%# end %>
        </div>
        <div class="d-flex align-items-center">
          <% if user_signed_in? %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete,  class: "btn nav-btn text-white rounded fw-bold box-shadow  me-2 px-3 py-2", style: "font-size: 12px; background-color:#2146C7;" %>
            <%= image_tag current_user.avatar.url, class: 'rounded-circle flex-shrink-0 me-3 fit-cover', width: '50px', alt: 'avatar' %>
            <p class="pe-2 mt-3 d-none d-md-block" style="font-size: 14px; color:#2146C7;"><%= current_user.email %></p>
            <%#= link_to "アカウント編集", edit_user_registration_path, class: "dropdown-item text-main py-2 text-center" %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class: "btn nav-btn text-white rounded fw-bold box-shadow  me-2 px-3 py-2", style: "font-size: 12px; background-color:#2146C7;" %>
            <%= link_to "無料会員登録", new_user_registration_path, class: "btn nav-btn text-white rounded fw-bold box-shadow  me-2 px-3 py-2", style: "font-size: 12px; background-color:#2146C7;" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_pagetitle.html.erb
<div class="row d-flex justify-content-center">
    <div class="col d-flex justify-content-center text-center mt-5">
      <div class="col-10 col-md-6 mt-1">
        <div class="col-12 text-center pb-2">
          <p style="color: #2146C7;" class="w-lg-50 pt-3 fs-3 text-purple"><%= title %></p>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_validation_error.html.erb
<% if instance.errors.full_messages.present? %>
  <ul class="p-form__error priority">
    <% instance.errors.full_messages.each do |msg| %>
      <li class="p-form__error__item priority">
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HokaSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&amp;display=swap">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2? family=Kaisei+Decol:wght@500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
     <%= render 'layouts/flash' %>
    <div style="margin-top:100px"></div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>